---
- hosts: all
  become: yes
  tasks:
  - name: Create 'wheel' group if not present
    group:
      name: wheel
      state: present 

  - name: Set 'wheel' group to not enter password for sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
      
  - name: Enable ssh by password
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication yes'
      
  - name: Restart sshd
    service:
      name: sshd
      state: restarted

  - name: Set the host file with all boxes ips and names
    blockinfile:
      dest: /etc/hosts
      state: present
      block: | 
        192.168.60.4 workstation workstation.example.com
        192.168.60.5 servera servera.example.com
        192.168.60.6 serverb serverb.example.com
        192.168.60.7 serverc serverc.example.com
        192.168.60.8 serverd serverd.example.com
      
  - name: Add ansible user
    vars:
      ansible_pass: ansible
    user: 
      name: ansible 
      password: "{{ ansible_pass | password_hash('sha512', 'therandomsalt' ) }}"
      groups: wheel
      comment: "Ansible User" 
      generate_ssh_key: yes 
      ssh_key_bits: 2048 
      ssh_key_file: .ssh/id_rsa


- hosts: workstation.example.com
  become: yes
  tasks:
  - name: Activate epel
    yum:
      name: epel-release
      state: latest

  - name: Install python libs and git
    yum:
      name: 
        - ansible
        - git
        - python3
      state: latest
