---
- hosts: all
  become: yes
  tasks:
  - name: Create 'wheel' group if not present
    group:
      name: wheel
      state: present 

  - name: Set 'wheel' group to not enter password for sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
      
  - name: Enable ssh by password
    lineinfile:
      dest: /etc/ssh/sshd_config
      state: present
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication yes'
      
  - name: Restart sshd
    service:
      name: sshd
      state: restarted

  - name: Set the host file with all boxes ips and names
    blockinfile:
      dest: /etc/hosts
      state: present
      block: | 
        192.168.60.4 controller
        192.168.60.5 web
        192.168.60.6 db
      
  - name: Add ansible user
    user: 
      name: ansible 
      # The password is 'ansible'
      password: $6$ak.6MIWYWrEQFx$e2fozesGvytPbVdriuVYzxYbVB4NWG4kIhE/7EO0N5gggyHeROe.GIf98uF.zoCUpX9j9Yfs4UXzZOjFGmmnO0
      groups: wheel
      comment: "Ansible User" 
      generate_ssh_key: yes 
      ssh_key_bits: 2048 
      ssh_key_file: .ssh/id_rsa


- hosts: controller
  become: yes
  tasks:
  - name: Activate epel
    yum:
      name: epel-release
      state: latest

  - name: Install ansible
    yum:
      name: 
        - ansible
        - python2-pip
        - python-devel
        - git
      state: latest
