---
- hosts: all
  become: yes
  tasks:
  - user: 
      name: ansible 
      # The password is 'ansible'
      password: $6$ak.6MIWYWrEQFx$e2fozesGvytPbVdriuVYzxYbVB4NWG4kIhE/7EO0N5gggyHeROe.GIf98uF.zoCUpX9j9Yfs4UXzZOjFGmmnO0
      comment: "Ansible User" 
      generate_ssh_key: yes 
      ssh_key_bits: 2048 
      ssh_key_file: .ssh/id_rsa
